"""add_workout_athlete_modified

Revision ID: 16525b371421
Revises: 6617782cb06d
Create Date: 2026-03-10 14:10:50.839634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16525b371421'
down_revision: Union[str, Sequence[str], None] = '6617782cb06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('athlete_modified', sa.Boolean(), nullable=True))
    op.add_column('workouts', sa.Column('modification_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'modification_notes')
    op.drop_column('workouts', 'athlete_modified')
    # ### end Alembic commands ###
