"""add 11 features schema changes

Revision ID: 3101df48f60a
Revises: a3f9c2e81b04
Create Date: 2026-03-26 13:13:37.387968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3101df48f60a'
down_revision: Union[str, Sequence[str], None] = 'a3f9c2e81b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('muscle_group', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_catalog_id'), 'exercise_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_catalog_name'), 'exercise_catalog', ['name'], unique=False)
    op.add_column('strength_goals', sa.Column('goal_type', sa.String(), server_default='lift', nullable=False))
    op.add_column('strength_goals', sa.Column('qualitative_goal', sa.Text(), nullable=True))
    op.add_column('strength_goals', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.alter_column('strength_goals', 'exercise_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('strength_goals', 'starting_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('strength_goals', 'target_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('strength_goals', 'target_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('users', sa.Column('coach_onboarding_skip_fields', sa.Text(), nullable=True))
    op.add_column('workout_logs', sa.Column('rpe', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'description')
    op.drop_column('workout_logs', 'rpe')
    op.drop_column('users', 'coach_onboarding_skip_fields')
    op.alter_column('strength_goals', 'target_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('strength_goals', 'target_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('strength_goals', 'starting_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('strength_goals', 'exercise_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('strength_goals', 'is_completed')
    op.drop_column('strength_goals', 'qualitative_goal')
    op.drop_column('strength_goals', 'goal_type')
    op.drop_index(op.f('ix_exercise_catalog_name'), table_name='exercise_catalog')
    op.drop_index(op.f('ix_exercise_catalog_id'), table_name='exercise_catalog')
    op.drop_table('exercise_catalog')
    # ### end Alembic commands ###
