"""add_rest_seconds_to_exercises

Revision ID: 53a4f79d4dc6
Revises: 3101df48f60a
Create Date: 2026-03-31 13:54:48.040568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a4f79d4dc6'
down_revision: Union[str, Sequence[str], None] = '3101df48f60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('rest_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'rest_seconds')
    # ### end Alembic commands ###
