"""add_onboarding_fields

Revision ID: 6617782cb06d
Revises: 027c82d1ca8f
Create Date: 2026-03-10 13:58:55.004848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6617782cb06d'
down_revision: Union[str, Sequence[str], None] = '027c82d1ca8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('injuries', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'injuries')
    # ### end Alembic commands ###
