name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Runs automatically every 30 minutes
  workflow_dispatch: # Enables manual triggering via a button

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: NitinSPRao # The owner of the original upstream repository
          base: main # branch in freeweight-prod
          head: main # upstream branch in freeweight
